version: '3'
services:
  db:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pismo_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: ./app
    volumes:
      - "./go:/go"
    ports:
      - "8000:8000"
    tty: true    
    depends_on:
      - db
    
